Squashed 'docroot/profiles/custom/stanford_profile/' changes from 22ebe3b7..ffbb3db8
ffbb3db8 12.2.2
07c2bf8e Run tests on PHP 8.4 & 8.5 (#1079)
6ba35db6 D8CORE-8658: Update aria-label for secondary navigation (#1078)
a00eccc8 Uninstall js_cookie
c4802f38 Removed non-existent permission

git-subtree-dir: docroot/profiles/custom/stanford_profile
git-subtree-split: ffbb3db831c39bbc45081a968c4b5315d90b6b62

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -6,9 +6,13 @@ concurrency:
 jobs:
   phpunit:
     name: PHPUnit
+    strategy:
+      fail-fast: false
+      matrix:
+        php_version: [ 8.3, 8.4, 8.5 ]
     runs-on: ubuntu-latest
     container:
-      image: pookmish/drupal8ci:php8.3
+      image: pookmish/drupal8ci:php${{ matrix.php_version }}
     services:
       mysql:
         image: mysql:8.0
@@ -19,63 +23,28 @@ jobs:
           MYSQL_ROOT_PASSWORD: drupal
         ports:
           - 33306:3306
-        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
+        options: >
+          --health-cmd="mysqladmin ping"
+          --health-interval=10s
+          --health-timeout=5s
+          --health-retries=3
     steps:
-      - uses: actions/checkout@v4
-      - name: Restore Cache
-        uses: actions/cache@v4
+      - uses: actions/checkout@v6
         with:
-          path: |
-            vendor
-            docroot/core
-            docroot/libraries
-            docroot/modules/contrib
-          key: 12.x-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
-          restore-keys: |
-            12.x-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
-            12.x-${{ hashFiles('composer.json') }}-
-            12.x-
-      - name: Run Unit Tests
+          path: project
+      - name: Build project
+        env:
+          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
         run: |
-          git config --system --add safe.directory '*' &&
-          composer install -n &&
-          mkdir -p docroot/sites/simpletest &&
-          drush sws:source:tests:phpunit --db-host=mysql --db-pass=drupal --db-name=drupal --db-user=drupal --with-coverage &&
-          drush sws:tests:phpunit-coverage-check artifacts/phpunit/coverage/xml --clover-file=artifacts/phpunit/coverage/clover.xml -n
+          mysql -h mysql -P 3306 -u root -pdrupal -e 'SET GLOBAL max_allowed_packet=67108864;' --ssl=0 &&
+          composer global require su-sws/stanford-caravan:11.x-dev &&
+          ~/.config/composer/vendor/bin/sws-caravan phpunit /var/www/html --extension-dir=$GITHUB_WORKSPACE/project --with-coverage
       - name: Save Test Results
-        uses: actions/upload-artifact@v4
+        uses: actions/upload-artifact@v7
         if: failure()
         with:
-          name: unit-tests-results
-          path: $GITHUB_WORKSPACE/artifacts
-  sites_to_test:
-    name: Sites to test
-    runs-on: ubuntu-latest
-    container:
-      image: pookmish/drupal8ci:php8.3
-    outputs:
-      matrix: ${{ steps.set-matrix.outputs.matrix }}
-    steps:
-      - uses: actions/checkout@v4
-      - name: Restore Cache
-        uses: actions/cache@v4
-        with:
-          path: |
-            vendor
-            docroot/core
-            docroot/libraries
-            docroot/modules/contrib
-          key: 12.x-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
-          restore-keys: |
-            12.x-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
-            12.x-${{ hashFiles('composer.json') }}-
-            12.x-
-      - name: Get Sites
-        id: set-matrix
-        run: |
-          composer install -n &&
-          SITES=$(echo -n "$(drush sws:drush-config command.sws.options.multisites)" | jq -R -s -c 'split("\n") | sort') &&
-          echo "matrix=$SITES" >> $GITHUB_OUTPUT
+          name: d11-unit-tests-results
+          path: /var/www/html/artifacts
   shard_matrix:
     name: Test Shards
     runs-on: ubuntu-latest
@@ -85,26 +54,29 @@ jobs:
       - name: Generate Shard Matrix
         id: set-matrix
         run: |
-          n=${{ vars.TEST_SHARDS || 3 }} &&
+          n=${{ vars.TEST_SHARDS || 4 }} &&
           numbers=($(seq 1 $n)) &&
           json=$(printf '%s\n' "${numbers[@]}" | jq -R . | jq -s -c .) &&
           echo "Test shards: $json" &&
           echo "matrix=$json" >> $GITHUB_OUTPUT
   codeception:
     name: Codeception
-    needs: [sites_to_test, shard_matrix]
+    needs: [shard_matrix]
     strategy:
       fail-fast: false
       matrix:
-        site: ${{fromJSON(needs.sites_to_test.outputs.matrix)}}
-        suite: [acceptance, functional]
+        suite: [ acceptance, functional ]
+        php_version: [8.3, 8.4, 8.5]
         shard: ${{fromJSON(needs.shard_matrix.outputs.matrix)}}
     runs-on: ubuntu-latest
-    container:
-      image: pookmish/drupal8ci:php8.3
-      options: '--network-alias drupal8ci'
     env:
-      STANFORD_ENCRYPT: ${{secrets.STANFORD_ENCRYPT}}
+      DRUPAL_DATABASE_NAME: drupal
+      DRUPAL_DATABASE_USERNAME: drupal
+      DRUPAL_DATABASE_PASSWORD: drupal
+      DRUPAL_DATABASE_HOST: mysql
+    container:
+      image: pookmish/drupal8ci:php${{ matrix.php_version }}
+      options: '--network-alias drupal8ci'
     services:
       selenium:
         image: selenium/standalone-chrome:130.0
@@ -118,155 +90,41 @@ jobs:
           MYSQL_ROOT_PASSWORD: drupal
         ports:
           - 33306:3306
-        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
+        options: >
+          --health-cmd="mysqladmin ping"
+          --health-interval=10s
+          --health-timeout=5s
+          --health-retries=3
     steps:
-      - uses: actions/checkout@v4
-      - name: Restore Cache
-        uses: actions/cache@v4
+      - uses: actions/checkout@v6
         with:
-          path: |
-            vendor
-            docroot/core
-            docroot/libraries
-            docroot/modules/contrib
-          key: 12.x-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
-          restore-keys: |
-            12.x-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
-            12.x-${{ hashFiles('composer.json') }}-
-            12.x-
-      - name: Install Site
-        run: |
-          git config --system --add safe.directory '*' &&
-          mysql -h mysql -P 3306 -u root -pdrupal -e 'SET GLOBAL max_allowed_packet=67108864;' &&
-          rm -rf /var/www/html &&
-          ln -snf $GITHUB_WORKSPACE /var/www/html &&
-          mkdir -p -m 777 docroot/sites/default/files &&
-          if [ "${{ matrix.site }}" != "default" ]; then
-            rm -rf docroot/sites/${{ matrix.site }}/files &&
-            ln -sL ../default/files/ docroot/sites/${{ matrix.site }}/files
-          fi &&
-          apachectl stop &&
-          apachectl start &&
-          composer install -n &&
-          drush drupal:install --site=${{ matrix.site }} -n &&
-          drush image:derive thumbnail $(drush sql:query 'select uri from file_managed where uri like "%//media/%" limit 1') &&
-          drush xmlsitemap:rebuild &&
-          drush cr &&
-          mkdir -p artifacts/_data/
+          path: project
       - name: Run tests
+        env:
+          STANFORD_ENCRYPT: ${{ secrets.STANFORD_ENCRYPT }}
         run: |
-          n=${{ vars.TEST_SHARDS || 3 }} &&
-          PROFILE=`drush st --fields=install-profile --format=list` &&
-          drush codeception --site-domain=localhost --suite=${{ matrix.suite }} --test-dir=docroot/profiles/custom/$PROFILE/tests/codeception --shard=${{ matrix.shard }}/$n &&
-          if [ ! -f artifacts/report.html ]; then
-            exit 1
+          n=${{ vars.TEST_SHARDS || 4 }} &&
+          mysql -h mysql -P 3306 -u root -pdrupal -e 'SET GLOBAL max_allowed_packet=67108864;' --ssl=0 &&
+          composer global require su-sws/stanford-caravan:11.x-dev &&
+          ~/.config/composer/vendor/bin/sws-caravan codeception /var/www/html --extension-dir=$GITHUB_WORKSPACE/project --suites=${{ matrix.suite }} --shard=${{ matrix.shard }}/$n &&
+          if [ ! -f /var/www/html/artifacts/${{ matrix.suite }}/results.html ]; then
+              exit 1
           fi
       - name: Save Test Results
-        uses: actions/upload-artifact@v4
+        uses: actions/upload-artifact@v7
         if: always()
         with:
-          name: ${{ matrix.site }}-${{ matrix.suite }}-${{ matrix.shard }}-tests-results
-          path: artifacts
-  db_updates:
-    name: DB Updates
-    needs: sites_to_test
-    strategy:
-      fail-fast: false
-      matrix:
-        site: ${{fromJSON(needs.sites_to_test.outputs.matrix)}}
-    runs-on: ubuntu-latest
-    container:
-      image: pookmish/drupal8ci:php8.3
-      options: '--network-alias drupal8ci'
-    env:
-      STANFORD_ENCRYPT: ${{secrets.STANFORD_ENCRYPT}}
-    services:
-      mysql:
-        image: mysql:8.0
-        env:
-          MYSQL_DATABASE: drupal
-          MYSQL_USER: drupal
-          MYSQL_PASSWORD: drupal
-          MYSQL_ROOT_PASSWORD: drupal
-        ports:
-          - 33306:3306
-        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
-    steps:
-      - name: Install SSH key
-        uses: shimataro/ssh-key-action@v2
-        with:
-          key: ${{ secrets.SSH_KEY }}
-          name: id_rsa
-          known_hosts: ${{ secrets.KNOWN_HOSTS }}
-          if_key_exists: fail
-      - uses: actions/checkout@v4
-      - name: Restore Cache
-        uses: actions/cache@v4
-        with:
-          path: |
-            vendor
-            docroot/core
-            docroot/libraries
-            docroot/modules/contrib
-          key: 12.x-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
-          restore-keys: |
-            12.x-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
-            12.x-${{ hashFiles('composer.json') }}-
-            12.x-
-      - name: Sync and Update Site
-        run: |
-          git config --system --add safe.directory '*' &&
-          mysql -h mysql -P 3306 -u root -pdrupal -e 'SET GLOBAL max_allowed_packet=67108864;' &&
-          rm -rf /var/www/html &&
-          ln -snf $GITHUB_WORKSPACE /var/www/html &&
-          mkdir -p -m 777 docroot/sites/default/files &&
-          rm -rf docroot/sites/${{ matrix.site }}/files &&
-          ln -sL ../default/files/ docroot/sites/${{ matrix.site }}/files &&
-          apachectl stop &&
-          apachectl start &&
-          composer install -n &&
-          drush sa @${{ matrix.site }}.prod || exit 0 &&
-          drush drupal:sync --site=${{ matrix.site }} -n &&
-          curl -I http://localhost --fail
+          name: codeception-${{ matrix.suite }}-${{ matrix.shard }}
+          path: /var/www/html/artifacts
   all-tests-pass:
+    # This job will be skipped if the requirements pass. If any of the dependent
+    # jobs fail, this will run and throw an error, causing the PR to fail.
     name: All Tests Pass
-    needs: [phpunit, codeception, db_updates]
+    if: ${{ cancelled() || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure') }}
+    needs: [phpunit, codeception]
     runs-on: ubuntu-latest
     steps:
-      - run: echo 'Passed'
-  deploy:
-    name: Deploy Artifact
-    needs: [phpunit, codeception, db_updates]
-    runs-on: ubuntu-latest
-    container:
-      image: pookmish/drupal8ci:php8.3
-    steps:
-      - uses: actions/checkout@v4
-      - name: Restore Cache
-        uses: actions/cache@v4
-        with:
-          path: |
-            vendor
-            docroot/core
-            docroot/libraries
-            docroot/modules/contrib
-          key: 12.x-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
-          restore-keys: |
-            12.x-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
-            12.x-${{ hashFiles('composer.json') }}-
-            12.x-
-      - name: Install SSH key
-        uses: shimataro/ssh-key-action@v2
-        with:
-          key: ${{ secrets.SSH_KEY }}
-          name: id_rsa
-          known_hosts: ${{ secrets.KNOWN_HOSTS }}
-          if_key_exists: fail
-      - name: Deploy Artifact
-        run: |
-          git config --system --add safe.directory '*' &&
-          git config --global user.email "sws-developers@lists.stanford.edu" &&
-          git config --global user.name "Github Actions" &&
-          ssh-keyscan -t rsa svn-45197.prod.hosting.acquia.com >> /root/.ssh/known_hosts &&
-          composer install -n &&
-          drush sws:artifact:deploy -v -n
+      - run: |
+          echo "Some workflows have failed!"
+          exit 1
+
